### ISSUE TITLE
Error on deployment (relationship type)

### ISSUE THREAD

**Issue by majello** [SolidSpace/modern-events#2]
I get an error about an invalid number or relationship types with regard to 
'http://schemas.microsoft.com/sharepoint/2012/app/relationships/package-manifest'
when uploading/deploying.

Any ideas as to what to change.

**Comment by SolidSpace** [comment]
Sorry for my late reply. havent seen this report. 
fixed some issues in my last commit. there is a new version available for download. please give the new spkgg package a try. 
note: this is a sharepoint online only project
