### ISSUE TITLE
Mobil Phones creating an Event

### ISSUE THREAD

**Issue by BartPicDev** [SolidSpace/modern-events#5]
On mobil phones the save button and the abort button cant be seen and so you cant save an event. Im using the Mobile Chrome Browser on Android, I also tried it Edge, Firefox (mobile versions) etc. with the same result and several other people reported this bug too, the Save Button shortly shows up an then disapears, i added a GIF. Maybe you can avoid this by placing the buttons above the fields. 

https://user-images.githubusercontent.com/77620909/104957932-686cdf80-59cf-11eb-9389-1078964b0451.mp4

**Comment by BartPicDev** [comment]
I forgot to enable mobile view on the Websitefeatures site.

**Comment by BartPicDev** [comment]
I forgot to enable mobile view in the Websitefeatures.

**Comment by BartPicDev** [comment]
I´ll correct myself the problem still appears.

**Comment by SolidSpace** [comment]
I will no longer maintain this project.  This Webpart was build as a quick workaround for the missing SharePoint Calendar Webpart. A complete cleanup in code is needed to implement new features,. I recommend to switch over to one of this solutions

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-calendar

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/js-modern-calendar
