### ISSUE TITLE
New event by click on the date

### ISSUE THREAD

**Issue by BartPicDev** [SolidSpace/modern-events#6]
On some of my sites the whole calendar disappears if i click on a date to create a new event. If i deactivate the feauture the problem no longer appears, but i cant create events anymore. It seems like the Problem only appears if i dont create a custom list and just add a normal calendar.

**Comment by SolidSpace** [comment]
I will no longer maintain this project.  This Webpart was build as a quick workaround for the missing SharePoint Calendar Webpart. A complete cleanup in code is needed to implement new features,. I recommend to switch over to one of this solutions

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-calendar

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/js-modern-calendar
