### ISSUE TITLE
Options calendars

### ISSUE THREAD

**Issue by BartPicDev** [SolidSpace/modern-events#7]
In the (german) configuration options to set up the calendar the buttons for "Listenanzeige" and "Wochenanzeige" are reversed. Its only a problem in the configuration, if you choose the view within the calendar it works fine.

**Comment by SolidSpace** [comment]
I will no longer maintain this project.  This Webpart was build as a quick workaround for the missing SharePoint Calendar Webpart. A complete cleanup in code is needed to implement new features,. I recommend to switch over to one of this solutions

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-calendar

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/js-modern-calendar
